// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'mainTitle': string;
  'secondTitle': string;
  'thirdTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
